# -*- coding: utf-8 -*-
"""RegresiTugas(sleepdb).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11inA4i3oCEEeFmwDW2ZXZBXlXM37dmXp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
from scipy import stats

data = pd.read_excel("sleep_health_data.xlsx")
data

x = data.iloc[:, :-1].values
y = data.iloc[:, 1].values

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

len(x_train)

print(y_train)

data.shape

dataku = pd.DataFrame(data)
dataku.head

#Lakukan fitting simple linear regression train set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

#Visualisasi Grafik
plt.scatter(dataku.QualityofSleep, dataku.StressLevel)
plt.xlabel('Quality of Sleep')
plt.ylabel('Stress Level')
plt.title('Grafik Kualitas tidur terhadap Stress Level')
plt.show

#Visualisasi hasil pred pd trainset
plt.figure(figsize=(10,8)) #untuk uk plotnya

#biru as data observasi
plt.scatter(x_train, y_train, color = 'blue')

#garis merah as hasil pred dari ML
plt.plot(x_train, regressor.predict(x_train), color = 'red')

plt.xlabel('Quality of Sleep')
plt.ylabel('Stress Level')
plt.title('Grafik Kualitas tidur terhadap Stress Level(pada Train Set)')
plt.show

#Visualisasi hasil pred pd test set
plt.figure(figsize=(10,8)) #untuk uk plotnya

#biru as data observasi
plt.scatter(x_test, y_test, color = 'blue')

#garis merah as hasil pred dari ML
plt.plot(x_test, regressor.predict(x_test), color = 'red')

plt.xlabel('Quality of Sleep')
plt.ylabel('Stress Level')
plt.title('Grafik Kualitas tidur terhadap Stress Level(pada Test Set)')
plt.show

slope, intercept, r, p, std_err = stats.linregress(dataku.QualityofSleep, dataku.StressLevel)

#fungsi linier regresi
def myfunc(x):
  return slope*x+intercept

#untuk cek predict nya
stresslv = myfunc(9)
print(stresslv)