# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WyFU2icJVqqbAq1jhs7V_JMJ1dbKGQI8

untuk inisialisasi library yang digunakan
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pds

dataset = pds.read_csv('exam1.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

print(X)

print(y)

"""untuk menghilangkan missing values"""

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:, 5:8])
X[:, 5:8] = imputer.transform(X[:, 5:8])

print(X)

"""untuk encoding data ke matriks"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

print(X)

"""untuk encoding label atau y"""

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

print(y)

"""untuk membagi data ke training dan test set dengan data test 20% dan data train 80%"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

print(X_train)

print(X_test)

print(y_train)

print(y_test)

"""untuk melakukan scaling untuk memperkecil skala yang terdapat pada data"""

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 6:9] = sc.fit_transform(X_train[:, 6:9])
X_test[:, 6:9] = sc.transform(X_test[:, 6:9])

print(X_train)

print(X_test)