# -*- coding: utf-8 -*-
"""kmeans_sleepquality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wX1Qn2g3m7sQnyuKppCjDEzGSvcVMSLo
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('Sleep_health_and_lifestyle_dataset.csv')
X = dataset.iloc[:, [2, 10]].values

print(X)

from sklearn.cluster import KMeans
wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters = i, init = 'k-means++', random_state = 42)
    kmeans.fit(X)
    wcss.append(kmeans.inertia_)
plt.plot(range(1, 11), wcss)
plt.title('The Elbow Method')
plt.xlabel('Number of clusters')
plt.ylabel('WCSS')
plt.show()

kmeans = KMeans(n_clusters=4, init='k-means++',
                max_iter=300, n_init=10, random_state=0)
pred_y = kmeans.fit_predict(X)

plt.scatter(X[:,0], X[:,1])
plt.scatter(kmeans.cluster_centers_[:,0],
            kmeans.cluster_centers_[:,1], s=500, c='red')
plt.title('Clusters of Health based on Heart Rate dataset')
plt.xlabel('Age')
plt.ylabel('Heart Rate')

plt.show()